---
title: "variable_selection"
author: "Ruiyuan Ming"
date: "2024-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(leaps)
library(boot)
```

```{r}
bodyfat <- read.csv('../data/BodyFat_Cleaned.csv')
head(bodyfat)
```

```{r}
leaps1 <- regsubsets(BODYFAT~AGE+WEIGHT+HEIGHT+NECK+CHEST+ABDOMEN+HIP+THIGH+KNEE+ANKLE+BICEPS+FOREARM+WRIST,data=bodyfat,nbest=13)
plot(leaps1,scale='adjr2')
```

```{r}
leaps2 <- regsubsets(BODYFAT~AGE+ADIPOSITY+NECK+CHEST+ABDOMEN+HIP+THIGH+KNEE+ANKLE+BICEPS+FOREARM+WRIST,data=bodyfat,nbest=12)
plot(leaps2,scale='adjr2')
```

```{r}
shrinkage <- function(fit, k =10) {
  require(bootstrap)
  
  theta.fit <- function(x,y){lsfit(x,y)}
  theta.predict <- function(fit,x){cbind(1,x)%*%fit$coef}
  
  x <- fit$model[,2:ncol(fit$model)]
  y <- fit$model[,1]
  results <- crossval(x,y,theta.fit,theta.predict,ngroup=k)
  r2 <- cor(y,fit$fitted.values)^2
  r2cv <- cor(y,results$cv.fit)^2
  return (r2-r2cv)
}
```


```{r}
fit1 <- lm(BODYFAT~ABDOMEN,data=bodyfat)
fit2 <- lm(BODYFAT~WEIGHT+ABDOMEN,data=bodyfat)
fit3 <- lm(BODYFAT~WEIGHT+ABDOMEN+WRIST,data=bodyfat)
fit4 <- lm(BODYFAT~WEIGHT+ABDOMEN+WRIST+FOREARM,data=bodyfat)
fit5 <- lm(BODYFAT~WEIGHT + ABDOMEN + WRIST + FOREARM + NECK,data=bodyfat)
fit6 <- lm(BODYFAT~WEIGHT + ABDOMEN + WRIST + FOREARM + NECK + BICEPS,data=bodyfat)
```


```{r}
set.seed(1234)
s <- rep(0,6)
for(i in 1:1000){
  s[1] <- s[1] + shrinkage(fit1)
  s[2] <- s[2] + shrinkage(fit2)
  s[3] <- s[3] + shrinkage(fit3)
  s[4] <- s[4] + shrinkage(fit4)
  s[5] <- s[5] + shrinkage(fit5)
  s[6] <- s[6] + shrinkage(fit6)
}
r <- s/1000

variable_count <- 1:6
r_squared <- r

plot(variable_count, r_squared, type = "o", col = "blue",
     xlab = "Number of Variables", ylab = "Change of R-squared", 
     main = "Simplicity and Robustness Trade-off")

lines(variable_count, r_squared, type = "b", pch = 19, col = "blue")
```


